apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-app-pipeline
spec:
  workspaces:
    - name: shared-data
    - name: docker-credentials
  params:
    - name: GIT_URL
      type: string
      default: "https://github.com/moj-incub-auth/moj-vector-data.git"
    - name: GIT_BRANCH
      type: string
      default: "main"
    - name: CONTAINERFILE
      type: string
      default: "Dockerfile"
    - name: IMAGE_REFERENCE
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/moj-vector-data/search-app:latest"
  tasks:
    - name: fetch-source
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: git-clone
          - name: kind
            value: task 
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_BRANCH)
    - name: view-clone-content
      runAfter:
        - fetch-source
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: openshift-client
          - name: kind
            value: task 
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: manifest_dir
          workspace: shared-data
      params:
        - name: SCRIPT
          value: |

            DIR=./

            ls -l $DIR

            echo ; ls /
            echo; find /tekton -name "config.json" -o -name ".dockerconfigjson"
    - name: build-image
      runAfter: ["fetch-source"]
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: buildah
          - name: kind
            value: task
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig    
          workspace: docker-credentials
      params:
        - name: DOCKERFILE
          value: $(params.CONTAINERFILE)
        - name: IMAGE
          value: $(params.IMAGE_REFERENCE)
        - name: TLSVERIFY
          value: "false"
        - name: BUILD_EXTRA_ARGS
          value: >-
            --build-arg GIT_REF=$(tasks.fetch-source.results.COMMIT)
            --build-arg GIT_BRANCH=$(params.GIT_BRANCH)

#        - name: BUILD_EXTRA_ARGS
#          value: >-
#            --authfile $(workspaces.dockerconfig.path)/config.json
#            --push-authfile /tekton/creds/.docker/config.json
#            --build-arg GIT_REF=$(tasks.fetch-source.results.COMMIT)
#            --build-arg GIT_BRANCH=$(params.GIT_BRANCH)    

