apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ingest-govuk-design-piperun-
spec:
  pipelineRef:
    name: ingest-content-pipeline
  serviceAccountName: pipeline 
  params:
    # the URL of the GIT repo containing the source data to ingest
    - name: RESOURCE_GIT_URL
      value: "https://github.com/moj-incub-auth/govuk-design-system.git"
    - name: RESOURCE_GIT_BRANCH
      value: "main"
    - name: MILVUS_HOST
      value: "moj-milvus.moj-vector-data.svc.cluster.local"
    - name: RESOURCE_SUBDIRECTORY
      value: "govuk-design-system"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
