apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: vibe-ui-app-build-piperun-
spec:
  pipelineRef:
    name: build-app-pipeline
  serviceAccountName: pipeline 
  params:
    # the URL of the GIT repo containing the source data to ingest
    - name: GIT_URL
      value: "https://github.com/moj-incub-auth/vibe-ui.git"
    - name: GIT_BRANCH
      value: "main"
    - name: IMAGE_REFERENCE
      value: "image-registry.openshift-image-registry.svc:5000/moj-vector-data/gov-route-library:latest"
    - name: CONTAINERFILE
      value: "./Dockerfile"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    - name: docker-credentials  
      secret:
        secretName: pipeline-pull-push-auth
        items:
          - key: .dockerconfigjson
            path: config.json
