apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dwp-design-listener
spec:
  triggers:
    - bindings:
        - ref: git-repo-binding
      template:
        ref: dwp-design-template