apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: nhs-design-listener
spec:
  triggers:
    - bindings:
        - ref: git-repo-binding
      template:
        ref: nhs-design-template