apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vibe-ui-app-listener
spec:
  triggers:
    - bindings:
        - ref: git-repo-binding
      template:
        ref: vibe-ui-app-template